Make dashboard page
gsainfoteam/ziggle-ams-fe pull request #15
Opened 2023-11-01 11:51 UTC by qkralthf0115

2023-11-01 12:00 UTC, 2paperstar requested changes

2023-11-01 12:00 UTC, 2paperstar commented on src/pages/Dashboard/components/ApplicantInfo.tsx
> +  height: 377px;
377은 어떻게 나온 숫자죠?

2023-11-01 12:00 UTC, 2paperstar commented on src/pages/Dashboard/components/ApplicantInfo.tsx
> +  flex: 1 0 54px;
54 너무 애매한데요? 이거는 어디서 나온 숫자인가요..

2023-11-01 12:00 UTC, 2paperstar commented on src/pages/Dashboard/components/ApplicantInfo.tsx
> +const BaseAnswerCard = styled.div`
AnswerCard 보다는 GroupCard라는 이름이 더 좋아보여요

2023-11-01 12:00 UTC, 2paperstar commented on src/pages/Dashboard/components/ApplicantInfo.tsx
> +            })}
이렇게 바로 리턴하면 돼요
```suggestion
            {[...Array(50)].map((_, index) => (
              <ApplicantCard key={index}>
                <Logo>
                  <img src={paper} alt="paper icon" />
                  <div>학번</div>
                  <div>이름</div>
                </Logo>
                <Logo>
                  <Date>날짜</Date>
                  <img src={chat} alt="chat icon" />
                </Logo>
              </ApplicantCard>
            ))}
```

2023-11-01 12:00 UTC, 2paperstar commented on src/pages/Dashboard/components/ApplicantTrend.tsx
> +// import { SubTitle } from "chart.js";
얘는 의미 없는 주석이니까 지워주세요

2023-11-01 12:00 UTC, 2paperstar commented on src/pages/Dashboard/components/ApplicantTrend.tsx
> +    })
얘도
```suggestion
    .map((element, index) => dayjs()
        .subtract(index + 1, "days")
        .format("MMM DD"))
```

2023-11-01 12:00 UTC, 2paperstar commented on src/pages/Dashboard/components/ApplicantTrend.tsx
> +
의도한거 아니면 빈줄은 지워주세요

2023-11-01 12:00 UTC, 2paperstar commented on src/pages/Dashboard/components/Common.tsx
> +  gap: 0.7em;
0.75em? 처럼 2의 제곱수가 되게 가면 좋은데 아니여도 상관 없어용..

2023-11-01 12:00 UTC, 2paperstar commented on src/pages/Dashboard/components/ManagementBar.tsx
> +            <h2>D - #</h2>
이거 굳이 지금 PR에서 다룰 필요는 없을 것 같은데, #으로 되어있는거 위쪽으로 변수 분리해주세요!

2023-11-01 12:00 UTC, 2paperstar commented on src/pages/Dashboard/components/ManagerInfo.tsx
> +  width: 378px;
얘도 애매한 숫자가 들어있네요

2023-11-01 12:00 UTC, 2paperstar commented on src/pages/Dashboard/dashboard.tsx
> +// import calander from "./assets/calander.png";
여기도 의미없는 주석

2023-11-01 12:00 UTC, 2paperstar commented on tsconfig.json
> +  "include": ["src", "src/pages/Dashboard/components/.ScheduleManagement.tsx"],
이거 잘못 들어간 것 같아요 빼주세요

2023-11-01 12:05 UTC, qkralthf0115 commented on src/pages/Dashboard/components/ApplicantInfo.tsx
> +  height: 377px;
![image](https://github.com/gsainfoteam/ziggle-ams-fe/assets/126757594/63c87666-5482-404a-8575-1122c40a500e)
이 컴포넌트의 높이가 377px

2023-11-01 12:08 UTC, 2paperstar commented on src/pages/Dashboard/components/ApplicantInfo.tsx
> +  height: 377px;
![image](https://github.com/gsainfoteam/ziggle-ams-fe/assets/125528915/43bf1cd5-7f56-4daa-82a0-e5fbaf0153c6)
이 친구의 높이가 디자인 상으로 471px로 나오는데, 이걸 깔끔한 숫자인 480px로 맞추고 안쪽에 있는 카드 두개의 높이는 남는 공간을 채우는 방식으로 가면 좋을 것 같아요~

2023-11-01 12:13 UTC, qkralthf0115 commented on src/pages/Dashboard/components/ApplicantInfo.tsx
> +  flex: 1 0 54px;
![image](https://github.com/gsainfoteam/ziggle-ams-fe/assets/126757594/3ff54d9d-86a9-441a-85fe-62e267c88df1)
이 컴포넌트의 너비가 54px입니다.

2023-11-01 12:14 UTC, 2paperstar commented on src/pages/Dashboard/components/ApplicantInfo.tsx
> +  flex: 1 0 54px;
높이는 상관하지 말고 padding으로 사이즈를 차지하게 만드는게 나을 것 같아요

2023-11-14 07:41 UTC, qkralthf0115 commented on src/pages/Dashboard/components/ManagerInfo.tsx
> +  width: 378px;
관리자 정보 컴포넌트의 너비가 378px입니다.

2023-11-14 07:49 UTC, 2paperstar approved these changes
LGTM

2023-11-14 08:12 UTC, merged