🎉 BoardPage: Basic Funcionality Completed
gsainfoteam/ziggle-ams-fe pull request #7
Opened 2023-09-18 06:36 UTC by ParkJumyung

2023-09-18 12:08 UTC, 2paperstar requested changes

2023-09-18 12:08 UTC, 2paperstar commented on src/pages/Board/components/Carousel/ProjectCard.tsx
> +  }}
```suggestion
  transform: ${({ focused }) => focused && 'scale(0.8)'};
```

2023-09-18 12:08 UTC, 2paperstar commented on src/pages/Board/components/Carousel/MiniWidget/MiniWidget.tsx
> +function MiniWidget({ widgetElements }: { widgetElements: MiniWidgetProps }) {
이 컴포넌트의 재사용성을 잘 모르겠어요,, 그냥 부모 컴포넌트에서 전부 구현하는게 나을 것 같긴한데..?

2023-09-18 12:08 UTC, 2paperstar commented on src/pages/Board/components/Carousel/MiniWidget/MiniDueWidget.tsx
> +};
dayjs라는 라이브러리 사용을 고려해보시는건 어떨까요?

2023-09-18 12:08 UTC, 2paperstar commented on src/pages/Board/components/Carousel/Carousel.tsx
> +        `}
```suggestion
  right: ${({ direction }) => direction === 'right' && '20px'};
  left: ${({ direction }) => direction === 'left' && '20px'};
```

2023-09-18 12:08 UTC, 2paperstar commented on src/pages/Board/components/Carousel/Carousel.tsx
> +              focused={i == focusIndex}
```suggestion
              focused={i === focusIndex}
```

2023-09-18 12:08 UTC, 2paperstar commented on src/pages/Board/components/Carousel/Carousel.tsx
> +          <AddProjectCard focused={projectsData.length == focusIndex} />
```suggestion
          <AddProjectCard focused={projectsData.length === focusIndex} />
```

2023-09-18 12:08 UTC, 2paperstar commented on src/pages/Board/components/Carousel/Carousel.tsx
> +        {focusIndex < projectsData.length && (
`focusIndex < projectsData.length`에 대한 의미를 잘 담을 수 있는 변수명을 하나 만들어서 위쪽으로 분리해주세용

2023-09-18 23:20 UTC, 2paperstar requested changes
모달은 다른 PR에서 다룰 예정인가용??
아직 앞선 리뷰에서 resolved 되지 않은 comments들이 있는데, 확인 부탁드려요!

2023-09-18 23:20 UTC, 2paperstar commented on src/pages/Board/components/Carousel/useCarousel.tsx
> +    );
여기도 Math.min써서..!

2023-09-18 23:20 UTC, 2paperstar commented on src/pages/Board/components/Carousel/ProjectCard.tsx
> +  }}
이거랑 비슷한 수정사항이 다른 파일에도 있어요!! @ParkJumyung

2023-09-18 23:20 UTC, 2paperstar commented on src/pages/Board/components/Carousel/Carousel.tsx
> +        {focusIndex < projectsData.length && (
isNotEnd로 분리했으면 이것도 바꾸면 좋을 것 같네요

2023-09-18 23:20 UTC, 2paperstar commented on src/pages/Board/components/Carousel/ProjectCard.tsx
> +const Paper = styled.div<{ ProjectCardWidth: string; focused: boolean }>`
ProjectCardWidth를 굳이 프롭으로 넘겨받을 필요가 있을까요?

2023-09-18 23:20 UTC, 2paperstar commented on src/pages/Board/components/Carousel/ProjectCard.tsx
> +const Paper = styled.div<{ ProjectCardWidth: string; focused: boolean }>`
또, 괜찮다면 여기에서도 css variable을 사용하는게 좋을 것 같기도 해요.
(css variable은 상속이 됨)

2023-09-18 23:20 UTC, 2paperstar commented on src/pages/Board/components/Carousel/ProjectCard.tsx
> +[];
?

2023-09-18 23:20 UTC, 2paperstar commented on src/pages/Board/components/Carousel/useCarousel.tsx
> +      end_date: dayjs(projectData.end_date),
구두로 api 단에서 dayjs로 바꿔주면 좋겠다는 이야기를 했었는데, 그걸 모킹하려면 모킹한 async function을 만들고, 그게 ProjectsDataFromDB에서 가져온 값을 돌려주면 (+ dayjs변환) 돼요

2023-09-19 05:03 UTC, ParkJumyung commented
> 모달은 다른 PR에서 다룰 예정인가용?? 아직 앞선 리뷰에서 resolved 되지 않은 comments들이 있는데, 확인 부탁드려요!

모달은 다른 PR에서 다룰 예정입니다!

2023-09-19 05:25 UTC, no-ikjun commented on src/pages/Board/components/Carousel/cssConst.ts
> +export const CarouselWidth = "80vw";
?? 혹시 이거 80으로 하신 이유가 있나요 ??

2023-09-19 05:28 UTC, ParkJumyung commented on src/pages/Board/components/Carousel/cssConst.ts
> +export const CarouselWidth = "80vw";
화면 가로로 꽉차면 별로일 것 같아서 80으로 하긴 했는데 별 생각은 없었어요
100vw가 나을까요?

2023-09-19 05:30 UTC, no-ikjun commented on src/pages/Board/components/Carousel/cssConst.ts
> +export const CarouselWidth = "80vw";
80으로 하니 화면 중간에 잘리는 부분이 생겨서 살짝 불편한 것 같아요..ㅋㅋ
가운데 정렬하는데 문제만 없다면 꽉 채우는게 나을 것 같아요!!

2023-09-19 05:39 UTC, ParkJumyung commented
![IMG_1734](https://github.com/gsainfoteam/ziggle-ams-fe/assets/126857540/0a9f6e8c-a9e6-4160-93c1-858bbb5db8df)

iPad에서 보니까 버튼이 다 파란색인데 ios에서는 버튼의 color를 default로 파란색으로 바꾸나요? 애플 유저분들 확인해주세요.

2023-09-19 05:40 UTC, 2paperstar commented
normalize css 적용했을텐데 적용해도 저렇게 되려나요..
On Sep 19, 2023 at 2:39 PM +0900, 박주명 ***@***.***>, wrote:
> iPad에서 보니까 버튼이 다 파란색인데 ios에서는 버튼의 color를 default로 파란색으로 바꾸나요? 애플 유저분들 확인해주세요.
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because your review was requested.Message ID: ***@***.***>

2023-09-19 06:30 UTC, 2paperstar commented
> ![IMG_1734](https://user-images.githubusercontent.com/126857540/268851144-0a9f6e8c-a9e6-4160-93c1-858bbb5db8df.png)
> 
> iPad에서 보니까 버튼이 다 파란색인데 ios에서는 버튼의 color를 default로 파란색으로 바꾸나요? 애플 유저분들 확인해주세요.

모바일 사파리 이슈인가보네요..

2023-09-19 09:25 UTC, 2paperstar requested changes
전체적으로 케이스 통일이 안 된 부분이 있는 것 같아요. CamelCase말고 camelCase사용해주세요!

2023-09-19 09:25 UTC, 2paperstar commented on src/pages/Board/components/Carousel/MiniWidget/MiniRecruitStatWidget.tsx
> +}
카멜케이스 사용해주세요

2023-09-19 09:25 UTC, 2paperstar commented on src/pages/Board/components/Carousel/useCarousel.tsx
> +  }, []);
굳이 지금 PR에서 다룰 필요는 없을 것 같은데 react-query 사용을 고려해보시면 좋을 것 같아요!

2023-09-20 11:49 UTC, 2paperstar requested changes

2023-09-20 11:49 UTC, 2paperstar commented on src/pages/Board/components/Carousel/MiniWidget/MiniRecruitStatWidget.tsx
> +  `;
위로 넘겨요

2023-09-20 12:15 UTC, 2paperstar requested changes

2023-09-20 12:15 UTC, 2paperstar commented on src/pages/Board/components/Carousel/MiniWidget/MiniDueWidget.tsx
> +      }${dateDiff}`}</h3>
```suggestion
      <h3 style={{ color: isNotOverDue ? "green" : "#eb6263" }}>
        {`D${isNotOverDue ? "" : "+"}${dateDiff}`}
      </h3>
```

2023-09-20 12:15 UTC, 2paperstar requested changes
하나만 더..!!

2023-09-24 06:34 UTC, 2paperstar approved these changes
LGTM! 수고했어용 :)

2023-09-24 07:03 UTC, merged